### ISSUE TITLE
Test results do not work with TCN Forecasting

### ISSUE THREAD

**Issue by quantqtech** [Azure/automl-testdataset-preview#4]
when attempting to test a forecast with a TCN forecast model - get a Service Error: Service Temporarily Unavailable. Please try again later.  

Other forecasting model types seem to work.

**Comment by CESARDELATORRE** [comment]
Hi @quantqtech.
TCN forecast is currently/still not supported for the PRIVATE PREVIEW.
It'll be supported in the PUBLIC PREVIEW.

Thanks for your feedback! :)
