### ISSUE TITLE
UI issue - list of data sets in the drop down for the test set, is not searchable or scrollable

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/automl-testdataset-preview#7]
From Quentin K Fisher:

The list of data sets in the drop down for the test set, is not searchable or scrollable, if I’m beyond, say 20…   I can get around this by creating a new one, but then I’m building even more datasets vs just re-versioning ones I have.

**Comment by TonyJ1** [comment]
This issue is fixed. Thanks!
